USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/motorola/xt320/BoardConfigVendor.mk

COMMON_GLOBAL_CFLAGS += -DQCOM_HARDWARE -DTARGET7x27A

TARGET_ARCH := arm
TARGET_CPU_ABI  := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_BOARD_PLATFORM := msm7627a
TARGET_BOOTLOADER_BOARD_NAME := 7x27
# Try to use ASHMEM if possible (when non-MDP composition is used)
TARGET_GRALLOC_USES_ASHMEM := true
TARGET_NO_BOOTLOADER := true

TARGET_NO_KERNEL := false
TARGET_NO_RADIOIMAGE := true
# Signed boot image support
TARGET_CPU_SMP := true
BOARD_KERNEL_BASE    := 0x00200000
BOARD_KERNEL_PAGESIZE := 4096
#Spare size is (BOARD_KERNEL_PAGESIZE>>9)*16
BOARD_KERNEL_SPARESIZE := 128
#Spare size for 8 bit BCH ECC NAND
BOARD_KERNEL_2KPAGESIZE := 2048
BOARD_KERNEL_2KSPARESIZE := 64
TARGET_KERNEL_SOURCE := kernel/motorola/xt320
# TARGET_PREBUILT_KERNEL = device/motorola/xt320/kernel
TARGET_KERNEL_CONFIG := moto_xt320_defconfig


TARGET_BOOTIMG_SIGNED := true
BOARD_NO_SPEAKER := true # msm7627a doesn't have speaker
BOARD_NO_TOUCHSCREEN := false
TARGET_BOOTLOADER_BOARD_NAME := xt320
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_QCOM_FM := true
TARGET_HAVE_TSLIB := true

TARGET_AVOID_DRAW_TEXTURE_EXTENSION := true
TARGET_USES_16BPPSURFACE_FOR_OPAQUE := true

TARGET_CORTEX_CACHE_LINE_32 := true
TARGET_USE_SPARROW_BIONIC_OPTIMIZATION := true

BOARD_HAS_8BIT_BCHECC_SUPPORT := true
BOARD_KERNEL_BCHECC_SPARESIZE := 160

# Support to build images for 2K NAND page
BOARD_SUPPORTS_2KNAND_PAGE := true

TARGET_USES_UNCOMPRESSED_KERNEL := false

ARCH_ARM_HAVE_TLS_REGISTER := true
BOARD_EGL_CFG := device/qcom/$(TARGET_PRODUCT)/egl.cfg


BOARD_HAVE_MXT224_CFG := true

BOARD_KERNEL_CMDLINE := androidboot.hardware=qcom loglevel=1 kgsl.mmutype=nommu vmalloc=48M
BOARD_KERNEL_BASE := 0x00200000
BOARD_KERNEL_PAGESIZE := 2048

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 	  5505024 # 0x00540000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 	  7340032 # 0x00700000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 	149946368 # 0x08f00000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 	173015040 # 0x0a500000
BOARD_FLASH_BLOCK_SIZE := 		   131072 # 0x00020000
BOARD_PERSISTIMAGE_PARTITION_SIZE := 10485760
BOARD_CACHEIMAGE_PARTITION_SIZE := 41943040

# TARGET_USERIMAGES_USE_EXT4 := true
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_USE_CUSTOM_RECOVERY_FONT := '"font_7x16.h"'
BOARD_EGL_CFG := device/motorola/xt320/egl.cfg
TARGET_SPECIFIC_HEADER_PATH += device/motorola/xt320/include
TARGET_USES_ION := false

# Use CAF media driver variant for 7627a
TARGET_QCOM_MEDIA_VARIANT := caf

BOARD_USES_QCOM_HARDWARE := true
